services:
  ffc-techspike-customer-registry-eligibility:
    build:
      context: .
      target: production
    image: ffc-techspike-customer-registry-eligibility
    container_name: ffc-techspike-customer-registry-eligibility
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-customer-registry-eligibility-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      ELIGIBILITYREQUEST_QUEUE_ADDRESS: ${ELIGIBILITYREQUEST_QUEUE_ADDRESS:-ffc-techspike-customer-registry-eligibility}${MESSAGE_QUEUE_SUFFIX}
      CUSTOMERREGISTRYREQUEST_QUEUE_ADDRESS: ${CUSTOMERREGISTRYREQUEST_QUEUE_ADDRESS:-ffc-techspike-customer-registry-request}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      LAND_ENDPOINT: ${LAND_ENDPOINT:- https://environment.data.gov.uk/arcgis/rest/services/RPA/}
